# 2.2 Tokenizacion de texto

In [32]:
import os
import urllib.request
if not os.path.exists("the-verdict.txt"):
    url = ("https://raw.githubusercontent.com/rasbt/"
           "LLMs-from-scratch/main/ch02/01_main-chapter-code/"
           "the-verdict.txt")
    file_path = "the-verdict.txt"
    urllib.request.urlretrieve(url, file_path)

In [33]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

In [34]:
raw_text #Cargar el texto

'I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no great surprise to me to hear that, in the height of his glory, he had dropped his painting, married a rich widow, and established himself in a villa on the Riviera. (Though I rather thought it would have been Rome or Florence.)\n\n"The height of his glory"--that was what the women called it. I can hear Mrs. Gideon Thwing--his last Chicago sitter--deploring his unaccountable abdication. "Of course it\'s going to send the value of my picture \'way up; but I don\'t think of that, Mr. Rickham--the loss to Arrt is all I think of." The word, on Mrs. Thwing\'s lips, multiplied its _rs_ as though they were reflected in an endless vista of mirrors. And it was not only the Mrs. Thwings who mourned. Had not the exquisite Hermia Croft, at the last Grafton Gallery show, stopped me before Gisburn\'s "Moon-dancers" to say, with tears in her eyes: "We shall not look upon its like again"?\n\nWell!--even 

In [35]:
len(raw_text) #REvisar la cantidad de caracteres

20479

In [36]:
import re #Expresiones regulares permiten buscar patrones en textos
text="Hello, world. This, is a test."
result=re.split(r'(\s)',text) #Separar por espacios en  blanco
print(result)

['Hello,', ' ', 'world.', ' ', 'This,', ' ', 'is', ' ', 'a', ' ', 'test.']


In [37]:
result = re.split(r'([,.]|\s)', text) #Separar por espacios, comas y puntos
print(result)

['Hello', ',', '', ' ', 'world', '.', '', ' ', 'This', ',', '', ' ', 'is', ' ', 'a', ' ', 'test', '.', '']


In [38]:
result = [item for item in result if item.strip()] #Eliminar espacios que son innecesarios
print(result)

['Hello', ',', 'world', '.', 'This', ',', 'is', 'a', 'test', '.']


In [39]:
text="Hello, world. Is this-- a test?"
result = re.split(r'([,.:;?_!"()\']|--|\s)', text)#Agregar más signos de puntuación
result = [item.strip() for item in result if item.strip()] #Eliminar espacios que son innecesarios
print(result)

['Hello', ',', 'world', '.', 'Is', 'this', '--', 'a', 'test', '?']


## Aplicar a la historia completa

In [40]:
preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)
preprocessed = [item.strip() for item in preprocessed if item.strip()]
print(len(preprocessed)) #Reducen los tokens por que se eliminaron espacios y tokens vacíos
print(preprocessed[:30]) #Primeros 30 tokens

4690
['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in']


# 2.3 Convertir los tokes en IDtokens


## Tamaño del vocabulario

In [51]:
all_words=sorted(set(preprocessed))#Ordenar yEliminar los tokens duplicados
vocab_size=len(all_words) #Cantidad de tokens únicos
print(vocab_size)

1130


## Construir el vocabulario

In [45]:
vocab={token:integer for integer, token in enumerate(all_words)} #Agregar un numero entero a cada token

{'!': 0, '"': 1, "'": 2, '(': 3, ')': 4, ',': 5, '--': 6, '.': 7, ':': 8, ';': 9, '?': 10, 'A': 11, 'Ah': 12, 'Among': 13, 'And': 14, 'Are': 15, 'Arrt': 16, 'As': 17, 'At': 18, 'Be': 19, 'Begin': 20, 'Burlington': 21, 'But': 22, 'By': 23, 'Carlo': 24, 'Chicago': 25, 'Claude': 26, 'Come': 27, 'Croft': 28, 'Destroyed': 29, 'Devonshire': 30, 'Don': 31, 'Dubarry': 32, 'Emperors': 33, 'Florence': 34, 'For': 35, 'Gallery': 36, 'Gideon': 37, 'Gisburn': 38, 'Gisburns': 39, 'Grafton': 40, 'Greek': 41, 'Grindle': 42, 'Grindles': 43, 'HAD': 44, 'Had': 45, 'Hang': 46, 'Has': 47, 'He': 48, 'Her': 49, 'Hermia': 50, 'His': 51, 'How': 52, 'I': 53, 'If': 54, 'In': 55, 'It': 56, 'Jack': 57, 'Jove': 58, 'Just': 59, 'Lord': 60, 'Made': 61, 'Miss': 62, 'Money': 63, 'Monte': 64, 'Moon-dancers': 65, 'Mr': 66, 'Mrs': 67, 'My': 68, 'Never': 69, 'No': 70, 'Now': 71, 'Nutley': 72, 'Of': 73, 'Oh': 74, 'On': 75, 'Once': 76, 'Only': 77, 'Or': 78, 'Perhaps': 79, 'Poor': 80, 'Professional': 81, 'Renaissance': 82, 'Ri

In [50]:
for i, item in enumerate(vocab.items()):
    print(item)


('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)
('Ah', 12)
('Among', 13)
('And', 14)
('Are', 15)
('Arrt', 16)
('As', 17)
('At', 18)
('Be', 19)
('Begin', 20)
('Burlington', 21)
('But', 22)
('By', 23)
('Carlo', 24)
('Chicago', 25)
('Claude', 26)
('Come', 27)
('Croft', 28)
('Destroyed', 29)
('Devonshire', 30)
('Don', 31)
('Dubarry', 32)
('Emperors', 33)
('Florence', 34)
('For', 35)
('Gallery', 36)
('Gideon', 37)
('Gisburn', 38)
('Gisburns', 39)
('Grafton', 40)
('Greek', 41)
('Grindle', 42)
('Grindles', 43)
('HAD', 44)
('Had', 45)
('Hang', 46)
('Has', 47)
('He', 48)
('Her', 49)
('Hermia', 50)
('His', 51)
('How', 52)
('I', 53)
('If', 54)
('In', 55)
('It', 56)
('Jack', 57)
('Jove', 58)
('Just', 59)
('Lord', 60)
('Made', 61)
('Miss', 62)
('Money', 63)
('Monte', 64)
('Moon-dancers', 65)
('Mr', 66)
('Mrs', 67)
('My', 68)
('Never', 69)
('No', 70)
('Now', 71)
('Nutley', 72)
('Of', 73)
('Oh', 74)
('On', 75)
('Once', 76)
('Only', 77)
('

## Simple tokenizador

In [52]:
class SimpleTokenizerV1:
    def __init__(self, vocab):
        self.str_to_int = vocab # Diccionario que mapea tokens a números
        self.int_to_str = {i:s for s,i in vocab.items()}    # Diccionario inverso: números a tokens
    def encode(self, text):
        # Divide el texto usando expresiones regulares
        preprocessed = re.split(r'([,.?_!"()\']|--|\s)', text)
        # Elimina espacios en blanco y elementos vacíos
        preprocessed = [
            item.strip() for item in preprocessed if item.strip()
        ]
        # Convierte tokens a números usando el vocabulario
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
    def decode(self, ids):
        # Convierte números de vuelta a tokens y los une con espacios
        text = " ".join([self.int_to_str[i] for i in ids])
        # Elimina espacios antes de signos de puntuación
        text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
        return text

In [53]:
tokenizer=SimpleTokenizerV1(vocab)

In [91]:
text=""""It's the last he painted, you know,"
Mrs. Gisburn said with pardonable pride."""

In [ ]:
ids=tokenizer.encode(text)#Convertir el texto a números
print(ids)

[1, 56, 2, 850, 988, 602, 533, 746, 5, 1126, 596, 5, 1, 67, 7, 38, 851, 1108, 754, 793, 7]


In [ ]:
print(tokenizer.decode(ids))#Decodificar los ids de vuelta a texto

" It' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.


# 2.4 Tokens de contexto especiales

## Agregar tokens que no estan en el diccionario

In [109]:
all_token=sorted(list(set(preprocessed)))#lista de tokens únicos
all_token.extend(["<|unk|>", "<|endoftext|>"])#Agregar tokens especiales

vocab={token:integer for integer, token in enumerate(all_token)} #Agregar un numero entero a cada token

In [110]:
len(vocab) #Nuevo tamaño del vocabulario con tokens especiales

1132

In [111]:
for i, item in enumerate(list(vocab.items())[-5:]):
    print(item)

('younger', 1127)
('your', 1128)
('yourself', 1129)
('<|unk|>', 1130)
('<|endoftext|>', 1131)


## Tokenizer palabras desconocidas

In [116]:
class SimpleTokenizerV2:
    def __init__(self, vocab):
        self.str_to_int = vocab
        self.int_to_str = { i:s for s,i in vocab.items()}
    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [
            item.strip() for item in preprocessed if item.strip()
        ]
        preprocessed = [
            item if item in self.str_to_int
            else "<|unk|>" for item in preprocessed
        ]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids
    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        text = re.sub(r'\s+([,.:;?!"()\'])', r'\1', text)
        return text

In [117]:
tokenizer=SimpleTokenizerV2(vocab)

In [127]:
text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."
text = " ".join((text1, text2))
print(text)

Hello, do you like tea? In the sunlit terraces of the palace.


In [130]:
text = "doyouliketea?"

In [131]:
tokenizer.encode(text)

[1130, 10]

In [132]:
tokenizer.decode(tokenizer.encode(text))

'<|unk|>?'

# 2.5 Byte pair encodind

In [2]:
import tiktoken

In [3]:
tiktoken.__version__

'0.9.0'

In [6]:
tokenizer = tiktoken.get_encoding("gpt2") #Usar el tokenizador de GPT-2

In [7]:
text = (
"Hello, do you like tea? <|endoftext|> In the sunlit terraces"
"of someunknownPlace."
)

In [10]:
integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})#Agregar token especial
print(integers)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 1659, 617, 34680, 27271, 13]


In [ ]:
tokenizer.decode(integers)

'Hello, do you like tea? <|endoftext|> In the sunlit terracesof someunknownPlace.'

In [13]:
text = (
"<|endoftext|>"
)

In [17]:
enndtokens = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
print(enndtokens)

[50256]


low

low e r

low e s t

l, o, w, e, r, s, t, lo, low


El algoritmo subyacente al BPE descompone palabras que no están en su vocabulario predefinido en subunidades de subpalabra o incluso caracteres individuales, permitiéndole manejar palabras fuera del vocabulario. Por lo tanto, gracias al algoritmo BPE, si el tokenizer encuentra una palabra desconocida durante la tokenización, puede representarla como una secuencia de tokens de subpalabra o caracteres

## Ejercicio 2.1


In [21]:
text="Akwirw ier" #probar el tokenizazdor con esta palabra

In [22]:
integers=tokenizer.encode(text)

In [23]:
tokenizer.decode(integers)

'Akwirw ier'

# 2.6 Muestreo de datos con ventana deslizante

In [25]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()
enc_text = tokenizer.encode(raw_text)#Tokenizar el veredicto
print(len(enc_text))


5145


In [27]:
enc_sample = enc_text[50:]#Tomar una muestra del texto tokenizado 

[290, 4920, 2241, 287, 257, 4489, 64, 319, 262, 34686, 41976, 13, 357, 10915, 314, 2138, 1807, 340, 561, 423, 587, 10598, 393, 28537, 2014, 198, 198, 1, 464, 6001, 286, 465, 13476, 1, 438, 5562, 373, 644, 262, 1466, 1444, 340, 13, 314, 460, 3285, 9074, 13, 46606, 536, 5469, 438, 14363, 938, 4842, 1650, 353, 438, 2934, 489, 3255, 465, 48422, 540, 450, 67, 3299, 13, 366, 5189, 1781, 340, 338, 1016, 284, 3758, 262, 1988, 286, 616, 4286, 705, 1014, 510, 26, 475, 314, 836, 470, 892, 286, 326, 11, 1770, 13, 8759, 2763, 438, 1169, 2994, 284, 943, 17034, 318, 477, 314, 892, 286, 526, 383, 1573, 11, 319, 9074, 13, 536, 5469, 338, 11914, 11, 33096, 663, 4808, 3808, 62, 355, 996, 484, 547, 12548, 287, 281, 13079, 410, 12523, 286, 22353, 13, 843, 340, 373, 407, 691, 262, 9074, 13, 536, 48819, 508, 25722, 276, 13, 11161, 407, 262, 40123, 18113, 544, 9325, 701, 11, 379, 262, 938, 402, 1617, 261, 12917, 905, 11, 5025, 502, 878, 402, 271, 10899, 338, 366, 31640, 12, 67, 20811, 1, 284, 910, 11, 351, 10

In [30]:
context_size = 4#determina cuántos tokens se incluyen en la entrada.
x = enc_sample[:context_size]#entrada
y = enc_sample[1:context_size+1]#objetivo
print(f"x: {x}")
print(f"y:       {y}")

x: [290, 4920, 2241, 287]
y:       [4920, 2241, 287, 257]


## Predecir tokens

In [31]:
for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]
    print(context, "---->", desired)

[290] ----> 4920
[290, 4920] ----> 2241
[290, 4920, 2241] ----> 287
[290, 4920, 2241, 287] ----> 257


## Decoding tokens

In [32]:
for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]
    print(tokenizer.decode(context), "---->", tokenizer.decode([desired]))

 and ---->  established
 and established ---->  himself
 and established himself ---->  in
 and established himself in ---->  a


## PyTorch tensors

In [33]:
import torch

In [37]:
torch.__version__
from torch.utils.data import Dataset, DataLoader

In [39]:
class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        # Inicializar listas para almacenar pares de entrada-objetivo
        self.input_ids = []
        self.target_ids = []
        
        # Convertir el texto a tokens numéricos
        token_ids = tokenizer.encode(txt)
        
        # Crear ventanas deslizantes con el tamaño y paso especificados
        for i in range(0, len(token_ids) - max_length, stride):
            # Obtener secuencia de entrada actual
            input_chunk = token_ids[i:i + max_length]
            # Obtener secuencia objetivo (desplazada 1 posición)
            target_chunk = token_ids[i + 1: i + max_length + 1]
            # Convertir a tensores de PyTorch y guardar
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        # Retornar número total de pares entrada-objetivo
        return len(self.input_ids)

    def __getitem__(self, idx):
        # Retornar un par específico de entrada-objetivo
        # usado por el DataLoader de PyTorch
        return self.input_ids[idx], self.target_ids[idx]

In [42]:
def create_dataloader_v1(txt, batch_size=4, max_length=256, 
                        stride=128, shuffle=True, drop_last=True,
                        num_workers=0):
    # txt: Texto de entrada a procesar
    # batch_size: Tamaño del lote de datos (default: 4)
    # max_length: Longitud máxima de secuencia (default: 256)
    # stride: Tamaño del paso para la ventana deslizante (default: 128)
    # shuffle: Si mezcla los datos aleatoriamente (default: True)
    # drop_last: Si descarta el último lote incompleto (default: True)
    # num_workers: Número de trabajadores para cargar datos (default: 0)
    
    # Crear tokenizador GPT-2
    tokenizer = tiktoken.get_encoding("gpt2")
    
    # Crear dataset usando el tokenizador y parámetros
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)
    
    # Configurar y crear el DataLoader
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle, 
        drop_last=drop_last,
        num_workers=num_workers
    )
    
    return dataloader

In [40]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

In [43]:
dataloader = create_dataloader_v1(
    raw_text, batch_size=1, max_length=4, stride=1, shuffle=False
)
data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


In [44]:
second_batch = next(data_iter)
print(second_batch)

[tensor([[ 367, 2885, 1464, 1807]]), tensor([[2885, 1464, 1807, 3619]])]


## Ejercicio 2.2

In [57]:
dataloader = create_dataloader_v1(
    raw_text, batch_size=1, max_length=2, stride=2, shuffle=False
)
data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

[tensor([[ 40, 367]]), tensor([[ 367, 2885]])]


In [54]:
dataloader = create_dataloader_v1(
    raw_text, batch_size=1, max_length=8, stride=2, shuffle=False
)
data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

[tensor([[  40,  367, 2885, 1464, 1807, 3619,  402,  271]]), tensor([[  367,  2885,  1464,  1807,  3619,   402,   271, 10899]])]


In [62]:
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=4, stride=4,
    shuffle=False
)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Targets:
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


# 2.7 Creando embeddings de tokens

In [71]:
input_ids = torch.tensor([2, 3, 5, 1])

In [72]:
vocab_size = 6
output_dim = 3

In [73]:
torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [74]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [75]:
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


# 2.8 Codificación de posiciones de palabras

In [76]:
vocab_size = 50257
output_dim = 256
token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [77]:
max_length = 4
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=max_length,
    stride=max_length, shuffle=False
)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Token IDs:\n", inputs)
print("\nInputs shape:\n", inputs.shape)

Token IDs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Inputs shape:
 torch.Size([8, 4])


In [78]:
token_embeddings = token_embedding_layer(inputs)
print(token_embeddings.shape)

torch.Size([8, 4, 256])


In [80]:
context_length = max_length
pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)
pos_embeddings = pos_embedding_layer(torch.arange(context_length))
print(pos_embeddings.shape)


torch.Size([4, 256])


In [81]:
input_embeddings = token_embeddings + pos_embeddings
print(input_embeddings.shape)

torch.Size([8, 4, 256])
